# Generated by Django 5.0.1 on 2024-01-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_insight_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='insight_text',
        ),
    ]
