# Generated by Django 5.0.1 on 2024-01-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_insight_insight_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='added',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='published',
        ),
    ]
